<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Terminal Taglines
    |--------------------------------------------------------------------------
    |
    | A collection of humorous taglines for the terminal interface.
    | These are displayed randomly on the login screen.
    |
     */
    'taglines' => [
        "Now with 100% more terminal!",
        "Keyboards: Still cool since 1874!",
        "GUI-free since before it was trendy!",
        "Putting the 'fun' in 'function arguments'!",
        "Where backslashes go to multiply!",
        "Just like the movies, but nerdier!",
        "Endorsed by hackers with hoodies everywhere!",
        "Making you look busy since 1969!",
        "More powerful than a point-and-click pony!",
        "Making coworkers think you're a genius since forever!",
        "Warning: May cause terminal addiction!",
        "No icons were harmed in the making of this interface!",
        "Because real programmers don't click things!",
        "Carpal tunnel included at no extra charge!",
        "Where 'help' is just another command you need to learn!",
        "Frustration guaranteed or your sanity back!",
        "You had me at 'sudo'!",
        "Bringing the 80s back, one command at a time!",
        "Try our new invisible interface!",
        "Now with extra blinking cursor anxiety!",
        "More slashes than a horror movie!",
        "The only screen where ~/ means home!",
        "Less graphics, more panic!",
        "The Most Revolutionary OS Since Windows 95",
        "Where GUIs Go To Die And Real Work Gets Done",
        "All The Graphics Of 1982, All The Power Of 2025",
        "Making Mice Obsolete Since The Dawn Of Computing",
        "Embracing The Black Screen Of Productivity",
        "Because Right-Clicking Was Too Mainstream",
        "Where 'User-Friendly' Is Just A Myth We Tell Children",
        "Colorful Text: The Original Dark Mode",
        "Pretend You're A Hacker In Every 90s Movie Ever",
        "We Saved Millions On UI Designers",
        "Your Grandpa's Interface, But Cooler",
        "Where Typos Become Existential Crises",
        "The Hipster's Choice: Computing Before It Was Cool",
        "Turning Simple Tasks Into Arcane Incantations Since 1969",
        "Fewer Buttons, More Keyboards, Zero Forgiveness",
        "Where Tab Completion Is The Closest Thing To Magic",
        "Making Stack Overflow Your Homepage Since 2008",
        "Like A Smartphone But Without The 'Smart' Or The 'Phone'",
        "When You're Too Cool For Point-And-Click Civilization",
        "Successfully Intimidating Non-Tech People Since Forever",
        "Achieving Maximum Productivity Through Minimal Design",
        "Autocorrect? We Call That 'Recompiling'",
        "The Original Touchscreen: Just Touch The Screen And Nothing Happens",
        "Still Waiting For The Graphical Update Since 1971",
        "Where Every Command Is A Leap Of Faith",
        "Memory Management: You Remember The Commands",
        "Bringing You Yesterday's Interface... Tomorrow!",
        "When 'Intuitive' Means 'Memorize These 500 Commands'",
        "Graphics Are Just A Crutch For The Command-Impaired",
        "Where Every Error Message Is A Cryptic Haiku",
        "The Interface That Makes IT Support Drink Heavily",
        "All The Fun Of Coding With None Of The Market Value",
        "Where Blinking Cursors Cause Existential Dread",
        "Proving That Progress Is Overrated Since UNIX",
        "Because Clicking Icons Is Too Mainstream For You",
        "Making 'Did You Try Turning It Off And On Again?' Seem Advanced",
        "Where Scrolling Up Is The Only Form Of Documentation",
        "Because GUIs Are For People Who Don't Want Carpal Tunnel",
        "The Only Interface Where 'ls' Isn't A Typo",
        "Where The Learning Curve Resembles A Brick Wall",
        "Confusing Interns And CEOs Equally Since The 1970s",
        "Putting The 'Command' Back In 'Command Line'",
    ],
];
