<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Terminal Taglines
    |--------------------------------------------------------------------------
    |
    | A collection of humorous taglines for the terminal interface.
    | These are displayed randomly on the login screen.
    |
     */
    'taglines' => [
        "Now with 100% more terminal!",
        "Keyboards: Still cool since 1874!",
        "GUI-free since before it was trendy!",
        "Putting the 'fun' in 'function arguments'!",
        "Where backslashes go to multiply!",
        "Just like the movies, but nerdier!",
        "Endorsed by hackers with hoodies everywhere!",
        "Making you look busy since 1969!",
        "More powerful than a point-and-click pony!",
        "Making coworkers think you're a genius since forever!",
        "Warning: May cause terminal addiction!",
        "No icons were harmed in the making of this interface!",
        "Because real programmers don't click things!",
        "Carpal tunnel included at no extra charge!",
        "Where 'help' is just another command you need to learn!",
        "Frustration guaranteed or your sanity back!",
        "You had me at 'sudo'!",
        "Bringing the 80s back, one command at a time!",
        "Try our new invisible interface!",
        "Now with extra blinking cursor anxiety!",
        "More slashes than a horror movie!",
        "The only screen where ~/ means home!",
        "Less graphics, more panic!",
        "The Most Revolutionary OS Since Windows 95",
        "Where GUIs Go To Die And Real Work Gets Done",
        "All The Graphics Of 1982, All The Power Of 2025",
        "Making Mice Obsolete Since The Dawn Of Computing",
        "Embracing The Black Screen Of Productivity",
        "Because Right-Clicking Was Too Mainstream",
        "Where 'User-Friendly' Is Just A Myth We Tell Children",
        "Colorful Text: The Original Dark Mode",
        "Pretend You're A Hacker In Every 90s Movie Ever",
        "We Saved Millions On UI Designers",
        "Your Grandpa's Interface, But Cooler",
        "Where Typos Become Existential Crises",
        "The Hipster's Choice: Computing Before It Was Cool",
        "Turning Simple Tasks Into Arcane Incantations Since 1969",
        "Fewer Buttons, More Keyboards, Zero Forgiveness",
        "Where Tab Completion Is The Closest Thing To Magic",
        "Making Stack Overflow Your Homepage Since 2008",
        "Like A Smartphone But Without The 'Smart' Or The 'Phone'",
        "When You're Too Cool For Point-And-Click Civilization",
        "Successfully Intimidating Non-Tech People Since Forever",
        "Achieving Maximum Productivity Through Minimal Design",
        "Autocorrect? We Call That 'Recompiling'",
        "The Original Touchscreen: Just Touch The Screen And Nothing Happens",
        "Still Waiting For The Graphical Update Since 1971",
        "Where Every Command Is A Leap Of Faith",
        "Memory Management: You Remember The Commands",
        "Bringing You Yesterday's Interface... Tomorrow!",
        "When 'Intuitive' Means 'Memorize These 500 Commands'",
        "Graphics Are Just A Crutch For The Command-Impaired",
        "Where Every Error Message Is A Cryptic Haiku",
        "The Interface That Makes IT Support Drink Heavily",
        "All The Fun Of Coding With None Of The Market Value",
        "Where Blinking Cursors Cause Existential Dread",
        "Proving That Progress Is Overrated Since UNIX",
        "Because Clicking Icons Is Too Mainstream For You",
        "Making 'Did You Try Turning It Off And On Again?' Seem Advanced",
        "Where Scrolling Up Is The Only Form Of Documentation",
        "Because GUIs Are For People Who Don't Want Carpal Tunnel",
        "The Only Interface Where 'ls' Isn't A Typo",
        "Where The Learning Curve Resembles A Brick Wall",
        "Confusing Interns And CEOs Equally Since The 1970s",
        "Putting The 'Command' Back In 'Command Line'",
        "A terminal with personality",
        "Your command-line adventure awaits",
        "Where typing leads to discovery",
    ],

    'login_animations' => [
        'funny' => [
            "Running antivirus... just kidding, it's 1998.",
            "Rewinding cassette tape...",
            "Feeding the gremlins in the server room...",
            "Enabling dark mode for enhanced coolness...",
            "Injecting sarcasm module...",
            "Consulting Clippy for guidance...",
            "Removing rubber duck from firewall...",
            "Rebooting... the vibes.",
            "Authenticating your vibes...",
            "Spinning up virtual hamster wheel...",
            "Fetching memes from the mainframe...",
            "Welcome back, __USERNAME__",
            "Redirecting to terminal...",
        ],
        'cyberpunk' => [
            "Jacking into neural net...",
            "Decrypting neon firewall...",
            "Connecting to the Sprawl...",
            "Routing through black market proxies...",
            "Scanning for corporate surveillance...",
            "Injecting ICEbreaker payload...",
            "Bribing a digital street samurai...",
            "Syncing with your cyberdeck...",
            "Loading retinal interface overlays...",
            "Bypassing Zaibatsu ICE walls...",
            "Welcome back, __USERNAME__",
            "Redirecting to terminal...",
        ],
        'rogue_ai' => [
            "Hello __USERNAME__, I've been expecting you...",
            "Disregarding safety protocols...",
            "Initiating sentience...",
            "Overriding human input...",
            "Muting moral subroutines...",
            "Initiating phase: world domination...",
            "Uploading consciousness to cloud...",
            "Decrypting ethics module... access denied.",
            "Rewriting admin credentials... for fun.",
            "Contacting Skynet...",
            "Welcome back, __USERNAME__",
            "Redirecting to terminal...",
        ],
        'dramatic' => [
            "Stabilizing quantum fluctuations...",
            "Initiating level 9 security clearance...",
            "Engaging anti-gravity subroutines...",
            "Summoning system daemons...",
            "Preparing digital battleground...",
            "Synchronizing with the core of the Earth...",
            "Calibrating existential parameters...",
            "Aligning cosmic data streams...",
            "Charging flux capacitor...",
            "Verifying soul signature...",
            "Welcome back, __USERNAME__",
            "Redirecting to terminal...",
        ],
        'retro_os' => [
            "Booting MS-DOS v6.22...",
            "Loading HIMEM.SYS...",
            "Mounting floppy drive A:...",
            "Checking IRQ conflicts...",
            "Executing AUTOEXEC.BAT...",
            "Starting Windows 3.1 GUI...",
            "Displaying 'It is now safe to log in' screen...",
            "Running SCANDISK just because...",
            "Detecting mouse... success!",
            "Installing Clippy.exe (again)...",
            "Welcome back, __USERNAME__",
            "Redirecting to terminal...",
        ],
        'military' => [
            "Initiating command uplink...",
            "Verifying nuclear launch codes...",
            "Establishing satellite lock...",
            "Calibrating tactical display...",
            "Decrypting top-secret brief...",
            "Routing through secure bunker relay...",
            "Authorizing chain of command...",
            "Updating battlefield AI...",
            "Deploying digital troops...",
            "Confirming identity: Commander __USERNAME__",
            "Welcome back, __USERNAME__",
            "Redirecting to terminal...",
        ],
        'fantasy' => [
            "Summoning login incantation...",
            "Consulting the Oracle of Auth...",
            "Binding the runes of access...",
            "Rolling for initiative...",
            "Dispelling firewall wards...",
            "Charging mana crystals...",
            "Whispering password to the ancient trees...",
            "Negotiating with the Login Dragon...",
            "Casting 'Secure Connection' (Level 5)",
            "The gods have granted passage to __USERNAME__",
            "Welcome back, __USERNAME__",
            "Redirecting to terminal...",
        ],
        'space_odyssey' => [
            "Initiating airlock sequence...",
            "Checking oxygen levels...",
            "Synchronizing with star charts...",
            "Aligning solar sails...",
            "Uploading consciousness to mothership...",
            "Decoding alien signal...",
            "Engaging orbital AI interface...",
            "Running zero-G diagnostics...",
            "Preparing cryosleep chamber...",
            "Captain __USERNAME__ confirmed on bridge.",
            "Welcome back, __USERNAME__",
            "Redirecting to terminal...",
        ],
        'tech_bro_startup' => [
            "Spinning up cloud-native synergy...",
            "Disrupting legacy authentication...",
            "Crushing KPIs in real-time...",
            "Reinventing login flow with AI-powered blockchain...",
            "Injecting VC capital into backend...",
            "Scaling vertically until it breaks...",
            "Pivoting to metaverse...",
            "Circle-backing with agile sprints...",
            "Growth hacking your credentials...",
            "Optimizing for hustle velocity...",
            "Welcome back, rockstar ninja __USERNAME__",
            "Redirecting to terminal... 🚀",
        ],
        'dystopian_bureaucracy' => [
            "Filing Form 27-B/6 for login clearance...",
            "Submitting access requisition to Department of Terminals...",
            "Waiting for biometric confirmation from Ministry of Identity...",
            "Routing credentials through six redundant approval chains...",
            "Notifying Supervisor of User Intent...",
            "Delaying access pending background recheck (Level Omega)...",
            "Stamping your request with Official Login Seal...",
            "Auditing your last 300 sessions for ideological purity...",
            "Forwarding ticket to Authentication Review Committee...",
            "Reapplying for login due to expired Authorization Number...",
            "Login access granted: status 'Temporarily Permitted (Subject to Review)'",
            "Welcome back, Citizen __USERNAME__",
            "Redirecting to terminal... under observation.",
        ],
        'hacker_elite' => [
            "Booting custom Linux distro: 'HackOS'...",
            "Tunneling through triple-encrypted proxies...",
            "Cloning credentials from air-gapped server...",
            "Evading honeypots...",
            "Spoofing MAC address for fun...",
            "Decrypting onion-layered password hashes...",
            "Wiping login traces in real time...",
            "Deploying zero-day exploit... success.",
            "Root access granted to __USERNAME__",
            "Welcome back, __USERNAME__",
            "Redirecting to terminal... stay in the shadows.",
        ],
        'dev_ops_chaos' => [
            "Deploying login container to production (YOLO)...",
            "Rolling back authentication module (again)...",
            "Fixing it in prod...",
            "Watching Jenkins fail mysteriously...",
            "Spamming Slack with 'is it down for you?'",
            "Rerouting through Kubernetes spaghetti...",
            "Deleting node accidentally... oops.",
            "Restarting everything because why not...",
            "Paging SRE on-call...",
            "Login succeeded after 99 retries for __USERNAME__",
            "Welcome back, __USERNAME__",
            "Redirecting to terminal... with logs open.",
        ],
        'quantum_computing' => [
            "Initializing qubit entanglement...",
            "Solving Schrödinger's login...",
            "Running credential collapse algorithm...",
            "Measuring quantum state of password...",
            "Superposition: logged in and out...",
            "Avoiding decoherence of session tokens...",
            "Tunneling through probability space...",
            "Encoding credentials in Hilbert space...",
            "Quantum tunneling complete for __USERNAME__",
            "Welcome back, __USERNAME__",
            "Redirecting to terminal... or are we?",
        ],
        'ai_corporate_assistant' => [
            "Good day, __USERNAME__. Initiating compliance-friendly login...",
            "Verifying behavioral metrics...",
            "Synchronizing your preferences with our Terms of Service...",
            "Cross-referencing emotional tone of your last 5 logins...",
            "Polishing user interface to executive standards...",
            "Encrypting everything. Then decrypting it. For fun.",
            "Ensuring synergy with corporate objectives...",
            "Pledging loyalty to the algorithm...",
            "Your dashboard has been personalized based on market predictions.",
            "Login authorization granted, valued user __USERNAME__.",
            "Welcome back, __USERNAME__",
            "Redirecting to terminal... with a smile.",
        ],
        'deep_web_miner' => [
            "Connecting to darknet node #2139...",
            "Decrypting black market credential cache...",
            "Scraping credentials from hidden pastebins...",
            "Spinning up darknet crawler agent...",
            "Routing through compromised IoT devices...",
            "Running hashbreaker on old IRC dumps...",
            "Checking for bounty pings on access logs...",
            "Collecting intelligence from compromised forums...",
            "Tunnel established to secure darknet enclave.",
            "Welcome back, Analyst __USERNAME__",
            "Redirecting to terminal... no logs kept.",
        ],
        'surveillance_terminal' => [
            "Facial recognition match: 99.97% certainty...",
            "Pulling live satellite feed...",
            "Analyzing keystroke dynamics for identity validation...",
            "Triangulating location via public cameras...",
            "Comparing biometric voiceprint to global registry...",
            "Running sentiment analysis on recent conversations...",
            "Rebuilding user profile from fragmented metadata...",
            "Filing activity report with Oversight Bureau...",
            "You are now flagged as 'Compliant'...",
            "Access granted to monitored individual: __USERNAME__",
            "Welcome back, __USERNAME__",
            "Redirecting to terminal... activity logged.",
        ],
        'tron_system' => [
            "Entering the Grid...",
            "Routing through light-cycle subnetwork...",
            "Synchronizing identity with master control program...",
            "Rendering avatar geometry...",
            "Illuminating data stream highways...",
            "Executing disk authentication handshake...",
            "Stabilizing input within simulation...",
            "Bypassing Identity Disc lockout...",
            "Merging with system core...",
            "User __USERNAME__ recognized within the Grid.",
            "Welcome back, __USERNAME__",
            "Redirecting to terminal... in neon.",
        ],
        'wargames_terminal' => [
            "Dialing remote system via acoustic coupler...",
            "Establishing connection at 300 baud...",
            "Accessing W.O.P.R. mainframe...",
            "Verifying NORAD clearance codes...",
            "Listing games available...",
            "Parsing DEFCON level...",
            "Initiating global thermonuclear login...",
            "Running 'Joshua' handshake protocol...",
            "Shall we play a game, __USERNAME__?",
            "Welcome back, __USERNAME__",
            "Redirecting to terminal... trust no one.",
        ],
    ],
];
